spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monumental_trees_database?stringtype=unspecified
    username: user
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    # mixed: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2uotfikm.eu.auth0.com/

springdoc:
  api-docs:
    path: /api/v1/monumental-trees/docs
  swagger-ui:
    path: /api/v1/monumental-trees/swagger-ui

auth0:
  audience: https://monumental-trees/

server:
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always
