spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monumental_trees?stringtype=unspecified
    username: user
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    mixed: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2uotfikm.eu.auth0.com/
  cloud:
    gcp:
      logging:
        enabled: true

auth0:
  audience: https://monumental-trees/

server:
  compression:
    enabled: true
