spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monumental_trees
    username: user
    password: password
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration
    mixed: true

server:
  compression:
    enabled: true